DISTFILES += \
    app.json \
    index.json \
    login.json \
    new.json \
    online.json \
    register.json \
    top-menu.json \
    topics.json \
    user.json \
    dashboard.pro.user \
    cache.appcache \
    index.html \
    extra.html \
    js/jquery-ui-bootstrap-masterbs3/assets/css/old/bootstrap.min.css \
    js/jquery-ui-bootstrap-masterbs3/assets/css/old/docs.css \
    js/jquery-ui-bootstrap-masterbs3/assets/js/google-code-prettify/prettify.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/bootstrap.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/holder.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/html5shiv.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/jquery-1.9.1.min.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/jquery-migrate-1.2.1.min.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/jquery-ui-1.10.3.custom.min.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/less-1.4.2.min.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/vendor/respond.min.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/demo-extra.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/demo-map.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/demo.js \
    js/jquery-ui-bootstrap-masterbs3/assets/js/docs.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/gmap3/gmap3.min.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-ar.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-bg.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-bg1251.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-cat.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-cn.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-cs.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-da.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-de.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-dk.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-el.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-en.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-es.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-fa.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-fi.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-fr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-gl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-he.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-hr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-hr1250.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-hu.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-id.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-is.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-it.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-ja.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-kr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-lt.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-mne.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-nl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-no.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-pl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-pt-br.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-pt.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-ro.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-ru.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-sk.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-sr-latin.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-sr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-sv.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-th.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-tr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-tw.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-ua.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/i18n/grid.locale-vi.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/jquery-1.9.0.min.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/jquery.jqGrid.min.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/jquery.jqGrid.src.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/grid.addons.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/grid.postext.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/grid.setcolumns.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/jquery.contextmenu.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/jquery.searchFilter.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/jquery.tablednd.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/ui.multiselect.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-ar.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-bg.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-bg1251.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-cat.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-cn.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-cs.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-da.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-de.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-dk.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-el.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-en.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-es.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-fa.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-fi.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-fr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-gl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-he.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-hr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-hr1250.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-hu.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-id.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-is.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-it.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-ja.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-kr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-lt.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-mne.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-nl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-no.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-pl.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-pt-br.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-pt.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-ro.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-ru.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-sk.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-sr-latin.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-sr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-sv.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-th.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-tr.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-tw.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-ua.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/i18n/grid.locale-vi.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.base.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.celledit.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.common.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.custom.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.filter.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.formedit.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.grouping.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.import.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.inlinedit.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.jqueryui.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.loader.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.subgrid.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.tbltogrid.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/grid.treegrid.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/jqDnR.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/jqModal.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/jquery.fmatter.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/JsonXml.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-Date-Range-Picker/js/date.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-Date-Range-Picker/js/daterangepicker.jQuery.compressed.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-Date-Range-Picker/js/daterangepicker.jQuery.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/js/enhance.min.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/js/fileinput.jquery.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/wijmo/jquery.bgiframe-2.1.3-pre.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/wijmo/jquery.mousewheel.min.js \
    js/jquery-ui-bootstrap-masterbs3/third-party/wijmo/jquery.wijmo-open.1.5.0.min.js \
    js/jquery-ui-bootstrap-masterbs3/server.js \
    js/jquery-ui-bootstrap-masterbs3/package.json \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font/fontawesome-webfont.eot \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font/fontawesome-webfont.woff \
    js/jquery-ui-bootstrap-masterbs3/assets/fonts/glyphicons-halflings-regular.eot \
    js/jquery-ui-bootstrap-masterbs3/assets/fonts/glyphicons-halflings-regular.woff \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font/FontAwesome.otf \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font/fontawesome-webfont.ttf \
    js/jquery-ui-bootstrap-masterbs3/assets/fonts/glyphicons-halflings-regular.ttf \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/css/ellipsis-xbl.xml \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/css/ellipsis-xbl.xml \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/images/icon-generic.gif \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/images/icon-image.gif \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/images/icon-media.gif \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/images/icon-zip.gif \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/apple-touch-icon-114-precomposed.png \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/apple-touch-icon-144-precomposed.png \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/apple-touch-icon-57-precomposed.png \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/apple-touch-icon-72-precomposed.png \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/favicon.png \
    js/jquery-ui-bootstrap-masterbs3/assets/img/bootstrap-jquery-plugins-01.png \
    js/jquery-ui-bootstrap-masterbs3/assets/img/bootstrap-jquery-plugins-02.png \
    js/jquery-ui-bootstrap-masterbs3/assets/img/bootstrap-js-components.png \
    js/jquery-ui-bootstrap-masterbs3/assets/img/bs-docs-masthead-pattern.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_flat_0_999999_40x100.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_flat_0_aaaaaa_40x100.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_glass_55_fbf9ee_1x400.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_glass_65_ffffff_1x400.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_glass_75_dadada_1x400.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_glass_75_e6e6e6_1x400.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_glass_75_ffffff_1x400.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_highlight-soft_75_cccccc_1x100.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-bg_inset-soft_95_fef1ec_1x100.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_222222_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_2e83ff_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_428bca_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_454545_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_555555_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_888888_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_999999_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_cd0a0a_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_f0ad4e_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_f6cf3b_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/images/ui-icons_ffffff_256x240.png \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font/fontawesome-webfont.svg \
    js/jquery-ui-bootstrap-masterbs3/assets/fonts/glyphicons-halflings-regular.svg \
    js/jquery-ui-bootstrap-masterbs3/assets/ico/favicon.ico \
    js/jquery-ui-bootstrap-masterbs3/assets/css/bootstrap.min.css \
    js/jquery-ui-bootstrap-masterbs3/assets/css/docs.css \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font-awesome-ie7.min.css \
    js/jquery-ui-bootstrap-masterbs3/assets/css/font-awesome.min.css \
    js/jquery-ui-bootstrap-masterbs3/assets/js/google-code-prettify/prettify.css \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/jquery-ui-1.10.3.custom.css \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/jquery-ui-1.10.3.theme.css \
    js/jquery-ui-bootstrap-masterbs3/css/custom-theme/jquery.ui.1.10.3.ie.css \
    js/jquery-ui-bootstrap-masterbs3/less/style.min.css \
    js/jquery-ui-bootstrap-masterbs3/less/style2.min.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/css/ui.jqgrid.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/searchFilter.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/plugins/ui.multiselect.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/css/ui.jqgrid.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/src/css/ui.multiselect.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid.overrides.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-Date-Range-Picker/css/ui.daterangepicker.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-FileInput/css/enhanced.css \
    js/jquery-ui-bootstrap-masterbs3/third-party/wijmo/jquery.wijmo-open.1.5.0.css \
    js/jquery-ui-bootstrap-masterbs3/sidebyside/sidebyside.html \
    js/jquery-ui-bootstrap-masterbs3/theme/base/components.html \
    js/jquery-ui-bootstrap-masterbs3/theme/base/extra.html \
    js/jquery-ui-bootstrap-masterbs3/theme/base/index.html \
    js/jquery-ui-bootstrap-masterbs3/theme/base/map.html \
    js/jquery-ui-bootstrap-masterbs3/theme/united/components.html \
    js/jquery-ui-bootstrap-masterbs3/theme/united/extra.html \
    js/jquery-ui-bootstrap-masterbs3/theme/united/index.html \
    js/jquery-ui-bootstrap-masterbs3/theme/united/map.html \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/demo.html \
    js/jquery-ui-bootstrap-masterbs3/third-party/jQuery-UI-Date-Range-Picker/index.html \
    js/jquery-ui-bootstrap-masterbs3/components.html \
    js/jquery-ui-bootstrap-masterbs3/extra.html \
    js/jquery-ui-bootstrap-masterbs3/index.html \
    js/jquery-ui-bootstrap-masterbs3/map.html \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/alerts.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/badges.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/bootstrap.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/breadcrumbs.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/button-groups.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/buttons.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/carousel.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/close.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/code.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/component-animations.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/dropdowns.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/forms.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/glyphicons.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/grid.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/input-groups.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/jumbotron.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/labels.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/list-group.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/media.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/mixins.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/modals.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/navbar.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/navs.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/normalize.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/pager.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/pagination.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/panels.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/popovers.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/print.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/progress-bars.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/responsive-utilities.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/scaffolding.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/tables.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/theme.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/thumbnails.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/tooltip.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/type.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/utilities.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/variables.less \
    js/jquery-ui-bootstrap-masterbs3/less/bootstrap/wells.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/accordion.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/autocomplete.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/base.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/button.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/core.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/datepicker.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/dialog.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/icons.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/jq-ui-bootstrap-mixin-adapter.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/jq-ui-bootstrap-variable-adapter.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/jq-ui-bootstrap.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/menu.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/misc.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/progressbar.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/resizable.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/selectable.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/slider.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/spinner.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/tabs.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/toolbar.less \
    js/jquery-ui-bootstrap-masterbs3/less/jq-ui-bootstrap/tooltip.less \
    js/jquery-ui-bootstrap-masterbs3/less/theme-custom/colorPallet.txt \
    js/jquery-ui-bootstrap-masterbs3/less/theme-spacelab/bootswatch.less \
    js/jquery-ui-bootstrap-masterbs3/less/theme-spacelab/variables.less \
    js/jquery-ui-bootstrap-masterbs3/less/theme-united/bootswatch.less \
    js/jquery-ui-bootstrap-masterbs3/less/theme-united/variables.less \
    js/jquery-ui-bootstrap-masterbs3/less/thirdParty/enhanced.less \
    js/jquery-ui-bootstrap-masterbs3/less/thirdParty/font-awesome.less \
    js/jquery-ui-bootstrap-masterbs3/less/thirdParty/ui.daterangepicker.less \
    js/jquery-ui-bootstrap-masterbs3/less/thirdParty/wijmo-theming.less \
    js/jquery-ui-bootstrap-masterbs3/less/custom.less \
    js/jquery-ui-bootstrap-masterbs3/less/style.less \
    js/jquery-ui-bootstrap-masterbs3/less/style2.less \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/Changes.txt \
    js/jquery-ui-bootstrap-masterbs3/third-party/jqGrid/jqGrid/js/install.txt \
    js/jquery-ui-bootstrap-masterbs3/README.md
